require("plugins.tools.window-picker")
-- require("plugins.tools.wilder")
require("plugins.tools.vim-prettier")
require("plugins.tools.ts-autotag")
require("plugins.tools.treesitter")
require("plugins.tools.terminal")
require("plugins.tools.startup-time")
require("plugins.tools.schemastore")
require("plugins.tools.lualine")
require("plugins.tools.telescope")
require("plugins.tools.lazygit")
require("plugins.tools.gps")
require("plugins.tools.gitsigns")
require("plugins.tools.fidget")
require("plugins.tools.comment")
require("plugins.tools.colorizer")
require("plugins.tools.barbar")
require("plugins.tools.neo-tree")